shared:
    image: node:12

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - echo: echo doing nothing here

    # Deploy to beta environment and run tests
    beta:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - deploy-k8s: ./ci/k8s-deploy.sh
            - test: sleep 300 && curl --silent --fail -o /dev/null https://beta.sonar.screwdriver.cd
        environment:
            K8S_TAG: 8.4.1-community
            K8S_CONTAINER: sonarqube
            K8S_IMAGE: sonarqube
            K8S_HOST: kubernetes.default.svc
            K8S_DEPLOYMENT: beta-sonarqube
        secrets:
            # Talking to Kubernetes
            - K8S_TOKEN

    # Deploy to prod environment and run tests
    prod:
        requires: [beta]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - deploy-k8s: ./ci/k8s-deploy.sh
            - test: sleep 300 && curl --silent --fail -o /dev/null https://sonar.screwdriver.cd
        environment:
            K8S_TAG: 8.4.1-community
            K8S_CONTAINER: sonarqube
            K8S_IMAGE: sonarqube
            K8S_HOST: kubernetes.default.svc
            K8S_DEPLOYMENT: prod-sonarqube
        secrets:
            # Talking to Kubernetes
            - K8S_TOKEN
